"""empty message

Revision ID: 14228b25d6d7
Revises: 
Create Date: 2021-04-17 16:51:15.734896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14228b25d6d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candle_sticker_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open_value', sa.String(), nullable=False),
    sa.Column('close_value', sa.String(), nullable=False),
    sa.Column('max_value', sa.String(), nullable=False),
    sa.Column('min_value', sa.String(), nullable=False),
    sa.Column('periodicity', sa.String(), nullable=False),
    sa.Column('date_time', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candle_sticker_model')
    # ### end Alembic commands ###
